project:
  type: website
  output-dir: docs


website:
  title: "Madeline Blok"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: projects.qmd
      - href: research.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



